---
name: SVN-Notify-Mirror
version: 0.03602
author:
  - 'John Peacock <jpeacock@cpan.org>'
abstract: Keep a mirrored working copy of a repository path
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Module::Build: 0.2805
  SVN::Notify: 2.62
provides:
  SVN::Notify::Mirror:
    file: lib/SVN/Notify/Mirror.pm
    version: 0.03602
  SVN::Notify::Mirror::Rsync:
    file: lib/SVN/Notify/Mirror/Rsync.pm
    version: ''
  SVN::Notify::Mirror::SSH:
    file: lib/SVN/Notify/Mirror/SSH.pm
    version: ''
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
