---
abstract: 'Keep a mirrored working copy of a repository path'
author:
  - 'John Peacock <jpeacock@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVN-Notify-Mirror
provides:
  SVN::Notify::Mirror:
    file: lib/SVN/Notify/Mirror.pm
    version: 0.040
  SVN::Notify::Mirror::Rsync:
    file: lib/SVN/Notify/Mirror/Rsync.pm
    version: 0.040
  SVN::Notify::Mirror::SSH:
    file: lib/SVN/Notify/Mirror/SSH.pm
    version: 0.040
requires:
  Module::Build: 0.38
  SVN::Notify: 2.83
  YAML: 0.81
resources:
  license: http://dev.perl.org/licenses/
version: 0.040
